{% set version = '2.0.10' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-magicaxis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/magicaxis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/magicaxis/magicaxis_{{ version }}.tar.gz
  sha256: 1479fff8cbfe6576e6b7f58ac45ed28f7db86661b711d4d0f79143e6283871fa

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-rcolorbrewer
    - r-celestial >=1.4.1
    - r-mapproj
    - r-plotrix
    - r-sm
  run:
    - r-base
    - r-mass
    - r-rcolorbrewer
    - r-celestial >=1.4.1
    - r-mapproj
    - r-plotrix
    - r-sm

test:
  commands:
    - $R -e "library('magicaxis')"           # [not win]
    - "\"%R%\" -e \"library('magicaxis')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=magicaxis
  license: GPL-3
  summary: Functions to make useful (and pretty) plots for scientific plotting. Additional plotting
    features are added for base plotting, with particular emphasis on making attractive
    log axis plots.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - npavlovikj
    - conda-forge/r

# Package: magicaxis
# Type: Package
# Title: Pretty Scientific Plotting with Minor-Tick and Log Minor-Tick Support
# Version: 2.0.10
# Date: 2019-07-05
# Author: Aaron Robotham
# Maintainer: Aaron Robotham <aaron.robotham@uwa.edu.au>
# Description: Functions to make useful (and pretty) plots for scientific plotting. Additional plotting features are added for base plotting, with particular emphasis on making attractive log axis plots.
# License: GPL-3
# Suggests: imager
# Imports: grDevices, graphics, stats, celestial (>= 1.4.1), MASS, plotrix, sm, mapproj, RColorBrewer
# NeedsCompilation: no
# Packaged: 2019-07-05 03:41:00 UTC; aaron
# Repository: CRAN
# Date/Publication: 2019-07-05 04:30:03 UTC
