{% set version = "2.0.10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-magicaxis
  version: {{ version|replace("-", "_") }}

source:
  fn: magicaxis_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/magicaxis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/magicaxis/magicaxis_{{ version }}.tar.gz
  sha256: 3dbc2da02afc4ad91252faaf8d9d5522f73aaf85303e56586b5588a84b217414

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip  # [win]
  host:
    - r-base
    - r-mass
    - r-celestial >=1.4.1
    - r-mapproj
    - r-plotrix
    - r-sm
  run:
    - r-base
    - r-mass
    - r-celestial >=1.4.1
    - r-mapproj
    - r-plotrix
    - r-sm

test:
  commands:
    - $R -e "library('magicaxis')"  # [not win]
    - "\"%R%\" -e \"library('magicaxis')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=magicaxis
  license: GPL-3
  summary: Functions to make useful (and pretty) plots for scientific plotting. Additional plotting
    features are added for base plotting, with particular emphasis on making attractive
    log axis plots.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [not win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - npavlovikj
